### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by Guilhermeslucas**

### CODE REVIEW

**Comment by Guilhermeslucas** [comment]
Fixes #7 and #8

**Comment by AvinZarlez** [comment]
It shouldn't need the main.yml file, since linter-ci.yml is there and it seems like the same?

**Comment by fedeoliv** [comment]
TobiahZ you're right, looks like they are the same thing...any specific reason for this .yml @Guilhermeslucas ?

**Comment by Guilhermeslucas** [comment]
Github wasn't allowing me to create a action from a yaml that was already done!

**Pull request merged**
